# Site settings
title: zaitra.io
email: info@zaitra.io (TODO)
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description. (TODO)
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

# User setting
owner: Zaitra s.r.o.
email: info@zaitra.io (TODO)
facebook_username: zaitra.io (TODO)
twitter_username: zaitra.io (TODO)
github_username: zaitra.io (TODO)
address:  
  - line: Technická 23
  - line: Brno, Czech Republic
  # Feel free to add more lines here 
telephone: +421 944 244 120
copyright: Zaitra s.r.o.

# API settings
google_api_key: AIzaSyCUpqtM_NHtyv0TtqcOWxGDiLnpKtrYh00

# Build settings
markdown: kramdown